### ISSUE TITLE
Fails if the jar paths have spaces

### ISSUE THREAD

**Issue by rnett** [SgtSilvio/gradle-proguard#1]
If the jar paths have spaces, running the proguard task will fail with an error about the paths (in argument 2), where the path it reports is not the full path, just the part after the space.  I highly suspect this is due to not quoting the file path arguments.

**Comment by SgtSilvio** [comment]
Hi @rnett 
all file paths are already quoted between `"`.
Can you please provide more information - for example the error output and which OS you are using?
I will also try to reproduce it in a test.

**Comment by rnett** [comment]
I'm on windows, here's a build scan: https://scans.gradle.com/s/5b3tmupe5xkhw/console-log?task=:frontend:proguardJar
The path to the input jar is `C:\Users\jimne\Desktop\My Stuff\k8s-learning\frontend\build\libs\frontend-0.0.1-shadow.jar`.

**Comment by rnett** [comment]
And here's a reproducer (note the branch): https://github.com/rnett/k8s-learning/blob/proguard-failure-reproducer/frontend/build.gradle.kts#L121
You'll see it if you run `:frontend:proguardJar`

**Comment by SgtSilvio** [comment]
@rnett this plugin was never really tested on Windows, I pushed a new commit to master which should fix compatibility with Windows.
Once I am sure the fix works fully I will release a new version. It would be great if you could try out the newest commit.

**Comment by SgtSilvio** [comment]
@rnett version [0.3.1](https://github.com/SgtSilvio/gradle-proguard/releases/tag/v0.3.1) fixes file path escaping on Windows, so I close this issue now.
Please comment if it fixes also your issue or if there are additional problems.
