### ISSUE TITLE
Get configuration from configuration file

### ISSUE THREAD

**Issue by skitou** [SgtSilvio/gradle-proguard#3]
Hi, it will be nice to have a way to load the Proguard configuration from a file than from typing by hand all the parameters.

like configurationFile = "proguard_config.txt"

**Comment by SgtSilvio** [comment]
Hi @skitou 
This is already possible: you can use `rulesFiles.from("proguard.config.txt")`.
But keep in mind that the rules files must not contain any file configuration parameters (`-injars`, `-libraryjars`, `-outjars`, ...). These must be declared in Gradle as inputs and outputs for up-to-date checking and caching to work.
