### ISSUE TITLE
javaLauncher value

### ISSUE THREAD

**Issue by haliphax** [SgtSilvio/gradle-proguard#5]
I'm getting the following error after following the configuration in the README:

```
Execution failed for task ':services:my-service:proguardJar'.
> Cannot query the value of task ':services:my-service:proguardJar' property 'javaLauncher' because it has no value available.
```

Is there a configuration step that I missed?

**Comment by haliphax** [comment]
Looks like I was missing the toolchain configuration, though I only figured this out by looking at a closed issue. May be worth putting in the README's example config.

**Comment by SgtSilvio** [comment]
added some minimal examples to the readme in this commit: https://github.com/SgtSilvio/gradle-proguard/commit/0317ed6872b763690d713669018e11d42c12305b
