### ISSUE TITLE
Using this plugin with java 8?

### ISSUE THREAD

**Issue by drori200** [SgtSilvio/gradle-proguard#6]
I am trying to use this on a project with java 8 but by default the plugin tries to get JMODs which aren't a thing until j9+ 
Example is this:
jdkModules.add("${System.getProperty("java.home")}/lib/rt.jar")
Causes:
`Caused by: java.io.IOException: No such file or directory: C:\Program Files\Eclipse Adoptium\jdk-8.0.372.7-hotspot\jre\lib\rt.jar.jmod`

**Comment by SgtSilvio** [comment]
Hi @drori200,
The `jdkModules` can only be used with Java 9+.
`jdkModules` is mostly a convenience and translates to a `library` input for ProGuard.
For Java 8, you can add directly add a library:
```
    addLibrary {
        classpath.from("${System.getProperty("java.home")}/lib/rt.jar")
    }
```
